alter table USER add CREATED_AT, UPDATED_AT;
alter table PUBLICATION add CREATED_AT, UPDATED_AT;
alter table ACHIEVEMENT add CREATED_AT, UPDATED_AT;
alter table COMMENT add CREATED_AT, UPDATED_AT;
alter table COMMUNITY add CREATED_AT, UPDATED_AT;